### ISSUE TITLE
[feature_request] support for page sections in data keys

### ISSUE THREAD

**Issue by Castone22** [cheezy/data_magic#25]
Currently as far as I can tell without post processing the data hashes returned there isn't a way to handle page sections in data magic. 

Being able to do something like

```yaml
successful_search
  search: books
  advanced_search:
    author: r.l. Stein
    publish_date: 2002
```

Would be pretty helpful when trying to fill out a very complex form that was organized using page sections from page object.
